on:
    push:
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: checkout
            uses: actions/checkout@v4

        -   name: create documentation
            run: |
                ./run.py --software --doc --verbose --pseudo_tty_off
                ./run.py --doc --build --verbose --pseudo_tty_off

        -   name: upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: documentation
                path: 'doc/build/html'
